export const slides = [
  {
    html: '<p>Bonjour, je m\'appelle <strong class="tool">Brice.<span>Freelance</span></strong> Je suis <i>UIX</i> & <i>Print Designer</i> de<br/><a href="https://www.normandie.fr/" class="highlight" target="_blank">Normandie, France</a> <a href="https://www.normandie.fr/" target="_blank"><span class="flag"></span></a></p><p class="animated fadeInUp" id="networks"><a href="https://www.instagram.com/seraphinbrice/" target="_blank" class="instagram"></a><a href="https://dribbble.com/seraphinbrice" target="_blank" class="dribbble"></a><a href="mailto:hello@seraphinbrice.fr" target="_blank" class="mail"></a><a href="tel:+33618589268" target="_blank" style="margin-right: 0" class="phone"></a></p>',
  },
  {
    html: "<h1>Geek <b>en</b> freelance</h1><p>Je propose des <a href='https://www.adobe.com/fr/products/photoshop.html' target='_blank' class='ico psd'></a> ressources graphiques <i>Gratuites & Payantes</i> de qualité supérieure_<br/><br/>J'ai la particularité d'avoir la <i>Reconnaissance de Travailleur Handicapé (AAH)</i>, en effet je<br/>suis atteint d'une <span class='ico handicap'></span> <a class='highlight' href='https://www.academie-medecine.fr/cytopathies-mitochondriales/' target='_blank'>Myopathie Mitochondriale</a> (maladie génétique très rare)_</p><div class='services d-flex justify-content-between'><div><h2>Design Responsive</h2></div><div><h2>Formes Vectorielles</h2></div><div><h2>Pixel Perfect</h2></div></div><div class='d-flex justify-content-center'><a href='https://dribbble.com/seraphinbrice' target='_blank' class='button button__pink shake-little'>DRIBBLE PRO_</a><a href='https://graphiste.com/YouAreCreative' target='_blank' class='button button__blue shake-little'>MON PORTFOLIO_</a></div>",
  },
  {
    html: "<h1>Créatif <i>&</i> Passioné - Des <b>Pixels</b> Plein La Vue !</h1><p>Jeune <i>geek</i> passionné d'informatique, Designer Freelance <i>amoureux</i> de son indépendance, je suis doté d'une très bonne <i>Expérience</i> dans la<br/><i>conduite</i> de projets graphiques, & je donne toujours le <i>meilleur</i> de moi-même pour vous conduire au succès ___ !<br/><br/>On me décrit comme un <i>bourreau</i> de travail, & quand je ne me démène pas pour <i>mes clients</i>, j'essaie de <i>m'améliorer</i> encore & encore, en<br/>m'inspirant des dernières <i>tendances</i> du moment en matière de <i>graphisme</i> & <i>d'interface d'utilisateur</i>, en <i>expérimentant</i> de <i>nouvelles techniques</i>, en<br/>étudiant <i>l'ergonomie</i> des plateformes <i>les mieux conçues</i> du net, que je dissèque avec <i>classe</i> & <i>passion.</i><br/><br/>Structuré, organisé, <i>-un POIL trop perfectionniste-</i>, j'ai les yeux qui <i>“saignent”</i> à la vue d'un pixel mal intégré !<br/><br/>Dans les jeux de type “FPS”, mon instinct, mes réflexes & ma vue <i>“bionique”</i> laissent peu de chances à mes adversaires :)<br/>Le reste du temps, <i>-en BON Geek qui se respecte-</i>, entre deux opus, je visionne séries & films cultes de sci-fi.</p>",
  },
  {
    html: "<h1><i>Ma</i> Philosophie</h1><p><i>Autodidacte</i>, je ne crois qu'aux vertus du travail & de <i>l'Expérience</i> précieusement <i>Acquise sur le Terrain.</i> Plutôt que de me disperser dans des<br/><i>domaines d'expertise différents</i>, Je m'investis exclusivement dans ma spécialité : <i>le Design</i>, en vue de devenir <i>Meilleur</i> dans celle-ci <i>:)</i>. Une équipe<br/>de <i>Spécialistes</i> couvrant tout le champ des <i>Compétences</i> requises sera toujours <i>MEILLEURE</i> qu'une équipe de <i>-couteaux suisses-</i> !<br/><br/><i>Indépendant</i> & <i>Autonome</i>, je m'efforce de proposer le <i>Prix Juste</i>, déterminé par le nombre d'heures de <i>Travail Effectives</i> requises pour la réalisation<br/>du <i>Cahier des Charges</i> (Brief). Celui-ci est toujours conçu de façon à répondre au mieux aux <i>Besoins</i> & aux <i>Projets</i> du client. Le fait de travailler en<br/><i>partenariat</i> avec d'autres <i>Freelances</i> protège le client de TOUT risque de conflit d'intérêt interne, <i>-fréquent au sein des agences web-</i> !<br/><br/>Appartenant à une génération qui a grandi avec le NET, dont la <i>Culture</i> a été façonnée par ses multiples usages, je considère ce réseaux comme <i>le<br/>DERNIER espace</i> de <i>Liberté</i> & de <i>Partage</i>, permettant souvent de contourner la <i>Censure</i> ! Je suis un <i>Fervent Défenseur</i> de la <i>Neutralité</i> du web !</p>",
  },
  {
    html: "<h1><i>Ma</i> Déontologie</h1><p>Étant un pur graphiste, je suis contre toute forme de \"Travail Spéculatif\" (Concours de créations,<br/>maquettes graphiques avant contrat, mise en compétition de plusieurs designers, etc... = <i>TRAVAUX GRATUIT EN SOMME</i>)<br/>qui entraîne la déchéance de nos métirs et les dévalorisent.<br/><br/>Pour ma part, aucun travail ne sera effectué avant confirmation de la mission (via le biais de devis et contrats<br/>étayés et signés par les deux parties et une facture systématique après la fin des travaux).<br/><br/>Qu'est ce que le <i>Travail Spéculatif \"Spec Work\"</i> ?<br/><a href='www.youtube.com/watch?v=gemQQ0-RSyQ' target='_blank'>www.youtube.com/watch?v=gemQQ0-RSyQ</a> <i>(VO)</i><br/><a href='www.ecommerce-platforms.com/fr/articles/what-every-designer-should-know-about-spec-work' target='_blank'>www.ecommerce-platforms.com/fr/articles/what-every-designer-should-know-about-spec-work</a><br/><br/>Le <i>\"Spec Work\"</i> ne touche *pour l'instant que* le monde de la <i>Création Graphique</i>, par exemple on ne voit pas encore ce genre de<br/>demande dans un projet de Développement pur.<br/><br/><i>Bonne lecture !</i> Sb_</p>",
  },
];
